include windows.inc
include user32.inc
include kernel32.inc
include shell32.inc
include comctl32.inc
include comdlg32.inc

includelib user32.lib
includelib kernel32.lib
includelib shell32.lib
includelib comctl32.lib
includelib comdlg32.lib

WinMain				PROTO :DWORD,:DWORD,:DWORD,:DWORD
WndProc				PROTO :DWORD,:DWORD,:DWORD,:DWORD

IDD_DIALOG			equ 1000
IDD_DLG1            equ 1100

IDM_MENU			equ 10000
IDM_FILE_EXIT		equ 10001
IDM_HELP_ABOUT		equ 10101
IDM_INSERT          equ 10002
IDM_REMOVE          equ 10003

IDC_EDT1            equ 1001
IDC_LST1            equ 1002
IDC_PROCESS         equ 1003
IDC_BTN1            equ 1004
       

.const

ClassName			db 'DLGCLASS',0
AppName				db 'Dialog as main',0
AboutMsg			db 'MASM32 RadASM Dialog as main',13,10,'Copyright © MASM32 2001',0
RemoveDialog        PROTO :DWORD,:DWORD,:DWORD,:DWORD

.data?

hInstance			dd ?
CommandLine			dd ?
hWnd				dd ?
hEditDlg            dd ?
hList               dd ?
tmp                 dd ?
nIndex              dd ?
hEdit               dd ?
n                   dd ?

.data

szBuffer        db  300 dup(' ')
two             dd  2
x               dd  0